### ISSUE TITLE
plot.show() is not working on Spyder IDE

### ISSUE THREAD

**Issue by ncdingari** [jwkvam/plotlywrapper#20]
```
import plotlywrapper as pw
plot = pw.line(x=[1, 2, 3, 4], y=[4, 1, 3, 7])
plot.title('hello world')
plot.show()
```

However, `plot.save('test.html')` works

**Comment by jwkvam** [comment]
Thanks for letting me know. I don't use spyder, but I'll try it out later.

**Comment by jwkvam** [comment]
@ncdingari I pushed a fix to master, it'd be great if you could confirm this fixes your issue. Otherwise I'll make a release either later today or in the next couple days.

**Comment by ncdingari** [comment]
@jwkvam How to install from github master? 
`pip install --upgrade https://github.com/jwkvam/plotlywrapper/tree/master`

This gives error, BTW I am using Mac OS X

**Comment by jwkvam** [comment]
@ncdingari Sorry, it's because I'm using a flit instead of the typical setuptools. You need to have python 3 to use it. You can try the following:
```
pip install flit
git clone plotlywrapper
cd plotlywrapper
flit install
```
